- .circleci/composer.json
- .circleci/config.yml
This PR will
- Run tests on PRs
- Take the build folder and publish it to https://github.com/jsdrupal/drupal-admin-ui-dist which will then get picked up by packagist (at https://packagist.org/packages/justafish/drupal-admin-ui until we can get something on the drupal namespace)
> CircleCI Setup

- .env
- README.md
This changes the URL from /vfancy/build to /vfancy
> Remove build folder

- README.md
- admin_ui_support/admin_ui_support.info.yml
- admin_ui_support/config/install/rest.resource.permissions_collection.yml
- admin_ui_support/src/Plugin/rest/resource/PermissionsCollectionResource.php
- admin_ui_support/tests/src/Functional/rest/UserPermissionsResourceTest.php
Note: 
There is https://github.com/jsdrupal/drupal-admin-ui/issues/18 and
https://github.com/jsdrupal/drupal-admin-ui/issues/4 to simplify the setup in the future.
> Move the support module into the main repo

- package.json
- src/App.js
- src/components/05_pages/Permissions/Permissions.js
- src/components/06_wrappers/Default/Default.js
- src/styles/base.js
- yarn.lock
Adds a navigation menu (with hardcoded links for now) and some (temporary) bad CSS so it's usable
> Add nav menu

- .gitignore
- admin_ui_support/admin_ui_support.services.yml
- admin_ui_support/config/install/rest.resource.menu_tree.yml
- admin_ui_support/src/Normalizer/MenuLinkNormalizer.php
- admin_ui_support/src/Normalizer/MenuTreeNormalizer.php
- admin_ui_support/src/Plugin/rest/resource/MenuTreeResource.php
Example output:
```
{
"49990 Content system.admin_content": {
"subtree": {
"50000 Comments comment.admin": {
"subtree": [],
"hasChildren": false,
"inActiveTrail": false,
"options": {
"attributes": {
"id": "toolbar-link-comment-admin",
"class": [
"toolbar-icon",
"toolbar-icon-comment-admin"
],
"title": "List and edit site comments and the comment approval queue."
}
},
"link": {
"weight": "0",
"title": "Comments",
"description": "List and edit site comments and the comment approval queue.",
"menuName": "admin",
"url": "/d8/admin/content/comment"
}
}
},
"hasChildren": true,
"inActiveTrail": false,
"options": {
"attributes": {
"id": "toolbar-link-system-admin_content",
"class": [
"toolbar-icon",
"toolbar-icon-system-admin-content"
],
"title": "Find and manage content."
}
},
"link": { …
```
> WIP: Expose the menu tree for the admin toolbar

- admin_ui_support/src/Normalizer/MenuTreeNormalizer.php
- admin_ui_support/src/Plugin/rest/resource/MenuTreeResource.php
- src/components/06_wrappers/Default/Default.js
- src/reducers/application.js
> Make subtree data type consistently an array

- admin_ui_support/admin_ui_support.routing.yml
- admin_ui_support/admin_ui_support.services.yml
- admin_ui_support/src/Controller/DefaultController.php
- admin_ui_support/src/Controller/EmptyController.php
- admin_ui_support/src/Routing/RouteSubscriber.php
- src/App.js
- yarn.lock
Test instructions:
**Blocked by https://github.com/jsdrupal/drupal-admin-ui/pull/55 right now**
* Enable the module
* Ensure your-host/vfancy works in general
* Goto your-host/admin/people/permissions
* Ensure that the vfancy UI appears with the permission form preselected
> Redirect to the app

- README.md
Goes with https://github.com/jsdrupal/drupal-admin-ui-demo/pull/10
> Improve the installation docs given the new scripts in the other project

- admin_ui_support/src/Controller/JsonApiRequestHandler.php
- src/components/05_pages/Permissions/Permissions.js
- src/utils/api/api.js
Note: I tried to play around with using redux/sagas for this page, but I thought this PR would be a smaller change.
> Move role/permission fetching and posting into api && make the module compatible with jsonapi 1.15

- src/components/05_pages/Content/Content.js
Screenshot to show what this small change does:
Would love to here your comments or suggestions.
> Show content action buttons inline.

- src/actions/application.js
- src/components/06_wrappers/Default/Default.js
- src/reducers/application.js
> Allow closing drawer

- src/components/02_atoms/OpsModalButton/OpsModalButton.js
- src/components/05_pages/Content/Content.js
> Delete modal dialog

- src/components/05_pages/Content/Content.js
- src/reducers/content.js
> Add no content message

- admin_ui_support/admin_ui_support.routing.yml
> Add path override for admin/content.

- src/InitialRedirect.js
- src/components/01_subatomics/Table/Table.js
- src/components/05_pages/Permissions/Permissions.js
- src/components/05_pages/Reports/Dblog.js
- src/components/05_pages/Roles/Roles.js
- src/components/06_wrappers/Default/Default.js
- src/components/06_wrappers/ErrorBoundary/ErrorBoundary.js
Solves https://github.com/jsdrupal/drupal-admin-ui/issues/160.
> Import proptypes object

- admin_ui_support/admin_ui_support.routing.yml
- src/components/02_atoms/OpsModalButton/OpsModalButton.js
- src/components/05_pages/AddContent/AddContent.js
- src/components/05_pages/Content/Content.js
- src/routes.js
Implement #152 
Todo:
~~* 'node/add' links~~
~~* path override in admin_ui_support~~
> Implement add content page

- src/actions/application.js
- src/components/02_atoms/OpsModalButton/OpsModalButton.js
- src/components/05_pages/AddContent/AddContent.js
- src/components/05_pages/Content/Content.js
- src/components/05_pages/Permissions/Permissions.js
- src/components/05_pages/Reports/Dblog.js
- src/components/05_pages/Roles/Roles.js
- src/components/06_wrappers/Default/Default.js
- src/reducers/application.js
- src/reducers/content.js
- src/utils/api/api.js
- src/utils/api/errors.js
- yarn.lock
If you set `REACT_APP_DRUPAL_BASE_URL="http://localhost:8888"` instead of `REACT_APP_DRUPAL_BASE_URL="http://127.0.0.1:8888"` you get an annoying error and nothing works
> Show an error message if you messed up configuring this app

- src/components/02_atoms/Widgets/NumberTextfield.js
- src/components/05_pages/NodeForm/UiMetadata.js
- src/components/05_pages/NodeForm/Widgets.js
> Initial number widget

- src/components/02_atoms/Widgets/NumberTextfield.js
- src/components/05_pages/AddContent/AddContent.js
- src/components/05_pages/NodeForm/index.js
> Add a vertical layout for the forms

- README.md
This may appear really trivial ... as part of #108  2 people have verified that this project works with node 10.
I want to update the documentation to imply that we can work with more that node  version 8
> Verified to works with node 10.6 ( #108 )

- package.json
- yarn.lock
> [#176] Downgrade babel dependency back to 6.x

- .storybook/addons.js
- .storybook/config.js
- README.md
- package.json
- src/components/02_atoms/Loading/Loading.stories.js
- src/components/02_atoms/Message/Message.stories.js
- yarn.lock
https://github.com/jsdrupal/drupal-admin-ui/issues/65
Run `yarn storybook`
> [#65] Add Storybook

- src/App.js
- src/components/06_wrappers/Default/Default.js
https://github.com/jsdrupal/drupal-admin-ui/issues/62
No UI changes.
Ensure that menu links are requested between route changes. This can be tested on the content page so that you first load the content list, and then click the add content button. Make sure that there's only one request for menu links.
> Render Default layout so that route change doesn't cause remounting

- src/utils/api/api.js
https://github.com/jsdrupal/drupal-admin-ui/issues/197
visit admin/reports/dblog
before patch "White screen of death"
after patch "expected table appears."
I fixed a DX issue, the  developer now gets at good stack report.
Bad watchdog route  is fixed
> Stop Dblog page from 404'ing #197

- src/components/02_atoms/Widgets/NumberTextfield.js
- src/components/05_pages/NodeForm/UiMetadata.js
- src/components/05_pages/NodeForm/index.js
https://github.com/jsdrupal/drupal-admin-ui/issues/194
Added suffix and prefix options, updated props
> Modified number to include suffix and prefix

- src/tests/Nightwatch/Tests/menu.js
https://github.com/jsdrupal/drupal-admin-ui/issues/209
NA
`yarn test:functional`
> Call end() on nightwatch tests

- src/components/05_pages/AddContent/AddContent.js
- src/tests/Nightwatch/Tests/AddContent.js
https://github.com/jsdrupal/drupal-admin-ui/issues/173
`yarn test:functional src/tests/Nightwatch/Tests/AddContent.js`
> Nigthwatch test for AddContent page (node/add)

- admin_ui_support/composer.json
> Update admin_ui_support dependencies

- src/components/05_pages/NodeForm/index.js
> Improve node form design

- src/components/05_pages/NodeForm/index.js
Resolves a small regression introduced by https://github.com/jsdrupal/drupal-admin-ui/pull/222
> Fix schema fetching

- admin_ui_support/admin_ui_support.info.yml
https://github.com/jsdrupal/drupal-admin-ui/issues/237
> Added openapi to list of dependencies

- LICENSE.md
- admin_ui_support/LICENSE.txt
- package.json
Solves https://github.com/jsdrupal/drupal-admin-ui/issues/233 hopefully
> Add license information

- src/components/02_atoms/FileUpload/FileUpload.stories.js
- src/components/02_atoms/Widgets/Widgets.stories.js
https://github.com/jsdrupal/drupal-admin-ui/issues/252
None
None 
In  code comments there are two sentences that  incorrectly  start with the word "The" when "To" is required.
> #252 Fix gramatical mistake.

- src/actions/content.js
- src/components/05_pages/NodeForm/index.js
- src/reducers/content.js
- src/utils/api/api.js
Fetching all the schema that OpenAPI provides is a bit much. This reduces that.
- Make sure `/node/add/recipe` still works.
> Fetch a single document.

- src/components/02_atoms/FileUpload/FileUpload.js
- src/components/02_atoms/Widgets/FileUploadWidget.js
- src/components/02_atoms/Widgets/Widgets.stories.js
https://github.com/jsdrupal/drupal-admin-ui/issues/193 and https://github.com/jsdrupal/drupal-admin-ui/issues/247
- Allow multiple and single file uploads.
- If single the upload option will be set to display none so no more images can be uploaded.
- Multiple will remain and allow for as many images to be uploaded.
- Added a button to upload area, this is so we have some accessibility for now. Will need to come back to this.
- If single file upload and more than one file is dropped, it will try to upload the first image, if there is an error this will display instead.
- Error check before uploading.
- Errors will display for every file that did not get uploaded.
- Error text taken from Drupal.
- Add the option to delete a file.
- Image preview, used …
> Various updates to file upload widget

- src/components/02_atoms/PageTitle/PageTitle.js
I'm getting following error on the node form:
I got this error message when accessing node form. Not sure if this needs some other steps to be reproducable given that no one else reported this before.
> Improve error handling in case of an empty title

- src/components/05_pages/NodeForm/index.js
I wanted to push this fix on the node save issue but forgot :(
> Minor fix in the nodeForm code

- src/components/02_atoms/Widgets/EntityReferenceAutocomplete.js
- src/components/02_atoms/Widgets/OptionsSelect.js
- src/components/02_atoms/Widgets/TimestampDatetime.js
This makes the form look much more consistent and cleaner because some of the field widgets were missing margin all together.
> Use normal margin consistently on field widgets

- src/components/02_atoms/FileUpload/FileUpload.js
- src/components/02_atoms/Widgets/FileUploadWidget.js
- src/utils/api/fieldItem.js
I think it would be nice if some people would test it.
Note:
* I'm using a freshly installed demo, so 8.7
> Try to fix the file upload

- .circleci/config.yml
https://github.com/jsdrupal/drupal-admin-ui/issues/<TODO>
> Add checkout step

- src/components/02_atoms/FileUpload/FileUpload.js
- src/components/02_atoms/Widgets/BooleanCheckbox.js
- src/components/02_atoms/Widgets/EntityReferenceAutocomplete.js
- src/components/02_atoms/Widgets/FileUploadWidget.js
- src/components/02_atoms/Widgets/NumberTextfield.js
- src/components/02_atoms/Widgets/OptionsSelect.js
- src/components/02_atoms/Widgets/StringTextfield.js
- src/components/02_atoms/Widgets/TimestampDatetime.js
- src/components/05_pages/NodeForm/index.js
- src/utils/api/schema.js
https://github.com/jsdrupal/drupal-admin-ui/issues/242
_LOLOL_
- Are there two columns?
_Alright_, this will need some styling help. Additionally since the information about which fields are supposed to exist in the secondary column is not available via an API, the field names are hard coded.
> Secondary column support

- src/components/05_pages/NodeForm/index.js
https://github.com/jsdrupal/drupal-admin-ui/issues/319
Visit 
http://localhost:3000/node/add/recipe
open Chrome's dev tools .. look at the console log..
before the PR there was a NodeForm: initialization warning
after the PR the warning is resolved.
> NodeForm initialisation generates warnings(#319)

- src/components/02_atoms/FileUpload/FileUpload.js
- src/components/02_atoms/PageTitle/PageTitle.js
- src/components/02_atoms/Widgets/BooleanCheckbox.js
- src/components/02_atoms/Widgets/DatetimeTimestamp.js
- src/components/02_atoms/Widgets/EntityReferenceAutocomplete.js
- src/components/02_atoms/Widgets/FileUploadWidget.js
- src/components/02_atoms/Widgets/NumberTextfield.js
- src/components/02_atoms/Widgets/OptionsSelect.js
- src/components/02_atoms/Widgets/StringTextfield.js
- src/components/05_pages/NodeForm/index.js
This mainly adjusts the input element widths and the paddings of the containers.
> Make the the app look more like the designs

- package.json
- src/components/02_atoms/Widgets/TextTextarea.css
- src/components/02_atoms/Widgets/TextTextarea.js
- src/components/02_atoms/Widgets/Widgets.stories.js
- src/components/05_pages/NodeForm/Widgets.js
- yarn.lock
Note: I went with draft.js as it was less work ;)
> Initial draft.js based editor

- src/components/05_pages/Content/Content.js
- src/components/05_pages/NodeForm/index.js
- src/tests/Nightwatch/Tests/AdminContent.js
https://github.com/jsdrupal/drupal-admin-ui/issues/136
- Make sure the loading bar shows.
- A bunch of the content page needed to be re-indented, sorry?
> Add loading bar component to Content Listing & Node Form pages.

- src/components/02_atoms/Widgets/TextTextarea.js
> Make the textarea consistent with other fields

- src/components/02_atoms/Widgets/BooleanCheckbox.js
- src/components/02_atoms/Widgets/FileUploadWidget.js
> Cleanup console errors due to bad props and PropType checking.

- src/components/02_atoms/FileUpload/FileUpload.stories.js
- src/components/02_atoms/OpsModalButton/OpsModalButton.stories.js
- src/components/02_atoms/Widgets/Widgets.stories.js
https://github.com/jsdrupal/drupal-admin-ui/issues/334
None
see the main issue for a complete explanation of why I want this....
Start the storybook server.
Visit http://localhost:9001/
For each component: The knobs panel has an array of controls allow users to set the state of the widget ( For example a user can toggle the required field on the DatetimeTimestamp widget and see visually what changes)
> Storybook: Apply interactivity consistently(#334)

- src/routes.js
> Enable node add for all bundles

- src/actions/content.js
- src/components/02_atoms/Widgets/DatetimeTimestamp.js
- src/components/02_atoms/Widgets/EntityReferenceAutocomplete.js
- src/components/02_atoms/Widgets/FileUploadWidget.js
- src/components/02_atoms/Widgets/NumberTextfield.js
- src/components/02_atoms/Widgets/StringTextfield.js
- src/components/02_atoms/Widgets/TextTextarea.js
- src/components/05_pages/Content/Content.js
- src/components/05_pages/NodeAddForm/index.js
- src/components/05_pages/NodeEditForm/index.js
- src/components/05_pages/NodeForm/index.js
- src/reducers/content.js
- src/routes.js
- src/utils/api/api.js
https://github.com/jsdrupal/drupal-admin-ui/issues/251
Current TODOs:
> Enabling editing a node

- src/components/05_pages/Content/Content.js
> Improve content filter styles

- src/components/05_pages/Content/Content.js
> Make filters visible even if there's no results

- src/actions/application.js
- src/actions/content.js
> Execute all actions when multiple actions are spawned at once

- src/components/05_pages/Content/Content.js
> Make node title a link

- src/actions/schema.js
- src/components/02_atoms/Widgets/OptionsSelect.js
- src/components/05_pages/NodeForm/index.js
- src/reducers/schema.js
- src/utils/api/api.js
- src/utils/api/schema.js
https://github.com/jsdrupal/drupal-admin-ui/issues/274
- Human readable names should be available on the options-select widget.
> Use human readable names on Options Select widget.

- src/components/05_pages/NodeForm/index.js
> Move created and uid fields to the right column on node form

- src/components/05_pages/AddContent/AddContent.js
https://github.com/jsdrupal/drupal-admin-ui/issues365
http://localhost:3000/node/add
The visual styling should be unchanged.
> #365  AddContent page over specifies CSS

- src/components/02_atoms/InlineMessage/InlineMessage.js
> Change inline message text color to white

- src/actions/content.js
> Add missing message severity on add content error

- src/components/05_pages/NodeEditForm/index.js
- can you save an edited node?
- is the bundle passed correctly.
> Fix minor issues with NodeEdit component

- src/actions/content.js
- src/components/05_pages/NodeForm/index.js
- src/reducers/content.js
https://github.com/jsdrupal/drupal-admin-ui/issues/293
- Make sure there is a default user for new content.
> Set a default for authored by field.

- src/actions/content.js
- src/components/01_subatomics/MessageHelpers/MessageSave.js
- src/components/02_atoms/SnackbarMessage/MessageHelpers.js
- src/components/02_atoms/SnackbarMessage/SnackbarMessage.js
https://github.com/jsdrupal/drupal-admin-ui/issues/<TODO>
> Show a message when a node is saved.

- src/actions/application.js
- src/reducers/application.js
https://github.com/jsdrupal/drupal-admin-ui/issues/356
Added the validation to check the Object instance.
1. Go to homepage `/`
2. Click on the `+` button at the bottom right corner.
3. There should be no error in the console window.
> Reducer type error fixed.

- src/components/05_pages/NodeAddForm/index.js
- src/components/06_wrappers/Default/Default.js
https://github.com/jsdrupal/drupal-admin-ui/issues/381
> Redirect the user after a succesfull node add

- src/components/02_atoms/Widgets/Widgets.stories.js
https://github.com/jsdrupal/drupal-admin-ui/issues/256
1) I have added a new storybook entry for EntityReferenceAutocomplete.
2) I have put the storybook definitions in alphabetical order
[ or I have moved DatetimeTimestamp ]
Visit 
http://localhost:9001/
A new widget story has been added.
> Add a storybook entry for EntityReferenceAutocomplete #256

- src/components/02_atoms/Widgets/DatetimeTimestamp.js
- src/components/05_pages/NodeForm/index.js
https://github.com/jsdrupal/drupal-admin-ui/issues/394
> Set default created on date.

- src/components/02_atoms/Widgets/TextTextarea.js
https://github.com/jsdrupal/drupal-admin-ui/issues/386
> Save also the format onChange of a TextTextarea

- src/components/01_subatomics/MessageHelpers/MessageSave.js
- src/components/06_wrappers/Default/Default.js
https://github.com/jsdrupal/drupal-admin-ui/issues/398
Type errors (console warnings) resolved.
> Type errors fixed.

- src/components/04_templates/ContentTable/ContentTable.js
- src/components/05_pages/Content/Content.js
Moving the content table to separate component so that making changes to the content listing would be easier. I tried to take the simplest approach possible here so this might need some further refactoring but this should be fine for now.
> Move content table to separate component

- src/components/05_pages/Content/ConfirmationDialog.js
- src/components/05_pages/Content/Content.js
https://github.com/jsdrupal/drupal-admin-ui/issues/403
> Show a dialog for bulk operations.

- src/components/02_atoms/Widgets/DatetimeTimestamp.js
https://github.com/jsdrupal/drupal-admin-ui/issues/406
Validation added for DateTimestamp defaultValue
> Datetime validation added.

- src/components/02_atoms/Widgets/BooleanCheckbox.js
1. By default values of the checkbox will reflect on UI i.e checked and unchecked.
2. Update the checkbox and save on reload you will see the changes as you made.
1. Go to which consist of checkbox element. e.g. node edit page checks the value of status, sticky and promote if it's true by default checkbox will be checked.
2. Update the checkbox and save the node page after reloading you will see the changes you made.
Checkbox state wasn't updating with respective values.. values coming from backend wasn't reflecting on the UI.
> Fixed checkbox state on UI with respect to it's values.

- src/actions/application.js
- src/actions/content.js
- src/actions/reports.js
- src/actions/reports.test.js
- src/actions/roles.js
- src/actions/schema.js
https://github.com/jsdrupal/drupal-admin-ui/issues/375
> Create specific setMessage method for each severity

- src/components/02_atoms/Widgets/EntityReferenceAutocomplete.js
https://github.com/jsdrupal/drupal-admin-ui/issues/418
> EntityReferenceAutocomplete: Autocomplete attribute added

- src/components/05_pages/NodeForm/index.js
https://github.com/jsdrupal/drupal-admin-ui/issues/395
> Show an alert when you have missing fields

- src/components/05_pages/NodeAddForm/index.js
- src/components/05_pages/NodeEditForm/index.js
- src/utils/api/content.js
https://github.com/jsdrupal/drupal-admin-ui/issues/384
_fwiw_, we really need to talk about a constraints system at Drupal Europe.
- make an article, don't upload an image, actually save the node.
> fixes #384

- src/App.js
- src/actions/content.js
- src/components/05_pages/NodeAddForm/index.js
- src/components/05_pages/NodeEditForm/index.js
- src/reducers/content.js
- src/tests/Nightwatch/Tests/NodeEdit.js
- src/utils/api/content.js
Follow up for https://github.com/jsdrupal/drupal-admin-ui/pull/357
resolves https://github.com/jsdrupal/drupal-admin-ui/issues/244
> Enable restoring lost edited content

- src/components/05_pages/NodeAddForm/index.js
- src/components/05_pages/NodeForm/index.js
Solves https://github.com/jsdrupal/drupal-admin-ui/issues/378
> Move the createEntity call to the node add form

- src/components/02_atoms/Widgets/EntityReferenceAutocomplete.js
> Entity type of referenced entities is not persisted on state update

- src/tests/Nightwatch/Tests/NodeEdit.js
I don't know why it fails, but here is the screenshot of it failing:
https://6219-121880923-gh.circle-artifacts.com/0/home/circleci/drupal-admin-ui-demo/drupal-admin-ui/reports/nightwatch/screenshots/NodeEdit/nodeEditFormRestoring_FAILED_Aug-30-2018-074443-GMT%2B0000.png
> Fix Nightwatch failure on CircleCI.

- .circleci/config.yml
- admin_ui_support/config/install/rest.resource.entity_schema_resource.yml
- admin_ui_support/src/Plugin/rest/resource/EntitySchemaResource.php
- src/actions/schema.js
- src/components/05_pages/NodeEditForm/index.js
- src/components/05_pages/NodeForm/index.js
- src/reducers/schema.js
- src/utils/api/api.js
https://github.com/jsdrupal/drupal-admin-ui/issues/435
- Create a new resource for entity schema at `/admin-api/entity-schema/{entityTypeID}/{nid}`
- Ensure that `/admin-api/entity-schema/{entityTypeID}/{nid}` returns the correct schema.
- How should set permissions, currently you have to give permission to the resource explicitly
- Tests
> Add entity schema rest resource

- src/actions/content.js
Co-authored-by: Matt Grill <matt.grill@acquia.com>
> Ensure the loading bar doesn't flickr while typing

- src/utils/api/fieldItem.test.js
#420 
Execute `yarn test:unit` from drupal-admin-ui
> IS-420: Add unit test coverage for fieldItem.js

- src/actions/application.js
- src/actions/content.js
- src/actions/reports.js
- src/actions/reports.test.js
- src/actions/roles.js
- src/actions/schema.js
- src/components/02_atoms/Widgets/NumberTextfield.js
- src/utils/api/api.js
- src/utils/api/errors.js
> Add some error handling

- src/components/05_pages/TaxonomyVocabulary/TaxonomyVocabulary.js
#462 
Visit taxonomy page and check the console for errors.
> Fixed console erorrs on taxonomy page.

- src/components/05_pages/TaxonomyVocabulary/TaxonomyVocabulary.js
https://github.com/jsdrupal/drupal-admin-ui/issues/464
- observe that things work and look like they should.
> Cleanup issues missing components with Taxonomy Vocabulary

- src/actions/content.js
- src/components/01_subatomics/MessageHelpers/MessageSave.js
Co-authored-by: Vishal Chandna <chandna.vishal1234@gmail.com>
https://github.com/jsdrupal/drupal-admin-ui/issues/444
>  The content creation message doesn't request content types from the API

- src/components/04_templates/ContentTable/ContentTable.js
- src/components/05_pages/Content/Content.js
- src/tests/Nightwatch/Tests/NodeEdit.js
https://github.com/jsdrupal/drupal-admin-ui/issues/487
> Fix flaky nightwatch tests.

- README.md
https://github.com/jsdrupal/drupal-admin-ui/issues/492
Link removed from the Readme
> Demo of vfancy link removed from Readme.

- package.json
- src/components/01_subatomics/MessageHelpers/MessageSave.test.js
- src/components/02_atoms/InlineMessage/InlineMessage.test.js
#477 
execute `yarn test:unit`
> IS-477: Adding unit test for messages

- package.json
- src/App.js
- src/components/02_atoms/FileUpload/FileUpload.js
- src/components/02_atoms/PageTitle/PageTitle.js
- yarn.lock
I tried to fix all the deprecation notices. However, due to a bug in Material UI that has been fixed already, when opening the confirmation dialog, there's a deprecation warning.
> Upgrade Material UI to the latest version

- src/components/02_atoms/Widgets/NumberTextfield.js
https://github.com/jsdrupal/drupal-admin-ui/issues/506
Storybook entry for NumberTextField throws exceptions
yarn run storybook 
See that NumberTextField now displays correctly.
Please note that as per 
https://github.com/jsdrupal/drupal-admin-ui/issues/506#issuecomment-431794761
I cannot justify why unsigned exists in the first place.
> 506: NumberTextField: Mishandled unsigned property

- src/components/05_pages/TaxonomyTermsOverview/TaxonomyTermsOverview.js
- src/components/05_pages/TaxonomyVocabulary/TaxonomyVocabulary.js
#474 
Go to taxonomy and taxonomy term overview page and check for the actions input label
Go to taxonomy term overview page and check the console for errors.
> issue-474: Added input label for actions and fixed console errors.

- .eslintrc.json
- packages/admin-ui/package.json
- packages/admin-ui/src/NoMatch.tsx
- packages/admin-ui/src/react-app-env.d.ts
- packages/admin-ui/tsconfig.json
- yarn.lock
https://github.com/jsdrupal/drupal-admin-ui/issues/64
> [#64] Adds TypeScript support and converts one simple component

- packages/admin-ui/package.json
https://github.com/jsdrupal/drupal-admin-ui/issues/543
> Greenkeeper/default/monorepo.react 16.6.3

- .eslintrc.json
- packages/admin-ui/package.json
- packages/admin-ui/src/NoMatch.tsx
- packages/admin-ui/src/react-app-env.d.ts
- yarn.lock
https://github.com/jsdrupal/drupal-admin-ui/issues/539
The problem this PR solves is that ts and tsx files do not show up in the eslint reports
think 
yarn run test:lint 
That argument also applied to 
yarn run eslint
This PR has errors - I think it is an important step to demonstrate publically the new errors are highlighted by the fix.
In a second push to this PR I will show the errors being fixed.
> esLinting: Check ts and tsx files. #539

- admin_ui_support/composer.json
https://github.com/jsdrupal/drupal-admin-ui/issues/564
run 
cd to admin_ui_support
composer validate 
see that by this PR one of the error/warnings  is cleaned up.
> SPDX license identifier #564

- admin_ui_support/src/Controller/DefaultController.php
It would be nice to help people when they forget to run the bundling process.
> Small DX improvement while working on extension points

- .circleci/config.yml
Fixes an issue with paths in the `dist` build step.
> Fix copy desintation in dist build step.

- packages/admin-ui/src/App.js
https://github.com/jsdrupal/drupal-admin-ui/issues/585
as per issue this fixes a lint failure.
> App:ServerRoutes Fixed lint failure

- package.json
Right now prettier isn't applied to the extension modules.
> Apply prettier onto extension modules as well

- packages/admin-ui/package.json
- packages/admin-ui/src/components/06_wrappers/ErrorBoundary/ErrorBoundary.js
- yarn.lock
https://github.com/jsdrupal/drupal-admin-ui/issues/594
In order to figure out the test failure in 594 it would be dramatically helpful if the error is actually rendered properly.
> Render errors with backtrace

- packages/admin-ui/src/components/05_pages/Content/Content.js
- packages/admin-ui/src/components/05_pages/NodeForm/index.js
- packages/admin-ui/src/components/06_wrappers/ErrorBoundary/ErrorBoundary.js
https://github.com/jsdrupal/drupal-admin-ui/issues/594
> Some additional work to catch errors

- .circleci/config.yml
- packages/admin-ui/package.json
The tests are failing. Let's pause for now.
> Disable failing Nightwatch tests.

- .circleci/config.yml
The dist process fails: https://circleci.com/gh/jsdrupal/drupal-admin-ui/9054 fails
> fix dist production

- .circleci/config.yml
See failure in https://circleci.com/gh/jsdrupal/drupal-admin-ui/9066
> more steps to be fixed on dist

- packages/admin-ui/.storybook/addons.js
- packages/admin-ui/package.json
- packages/admin-ui/src/components/02_atoms/Widgets/Widgets.stories.js
- packages/components/.storybook/addons.js
- packages/components/package.json
- packages/components/src/Components/Button/Button.stories.js
- yarn.lock
https://github.com/jsdrupal/drupal-admin-ui/issues/705
Added figma integration. As [decorator](https://github.com/hharnisc/storybook-addon-figma#or-use-the-decorator-to-put-the-same-design-on-each-story) 
[![Image from Gyazo](https://i.gyazo.com/e405250bedf818e0a5421871b5ba8fce.png)](https://gyazo.com/e405250bedf818e0a5421871b5ba8fce)
Added few components figma integration. In all other existing components stories i wasn't sure about their designs location. 
Current implementation of storybook is broken, so this pr will work 
with that small [fix](https://github.com/jsdrupal/drupal-admin-ui/issues/632#issuecomment-459645865)
> implemented figma. added few widgets.

- packages/components/src/Components/Button/Button.js
- packages/components/src/Components/FormElements/InputCheckbox/InputCheckbox.js
- packages/components/src/Components/FormElements/InputCheckbox/InputCheckbox.stories.js
- packages/components/src/Components/FormElements/Label.js
- packages/components/src/Utils/colors.js
#659 
1. Added initial implementation of checkbox component. 
2. Added functional colors variables.
3. Added storybook implementation. 
Taken current claro styles. So css not exactly same as on design provided. 
https://git.drupalcode.org/project/claro/blob/8.x-1.x/css/src/components/form--checkbox-radio.css
[![Image from Gyazo](https://i.gyazo.com/2620cb75209c5aa69a55be0f3c1ec21f.png)](https://gyazo.com/2620cb75209c5aa69a55be0f3c1ec21f)
Run storybook task.
> Added checkBox Component

- packages/components/src/Components/FormElements/InputRadio/InputRadio.js
- packages/components/src/Components/FormElements/InputRadio/InputRadio.stories.js
- packages/components/src/Utils/colors.js
https://github.com/jsdrupal/drupal-admin-ui/issues/661<TODO>
1. Added radio component.
2. Added new color `lightningGreen: '#26A769',` based on colour palette from design, also added colour variables for form elements, based on this PR https://github.com/jsdrupal/drupal-admin-ui/pull/712
3. Added storybook variations.
`npm run storybook`
> Added input radio component
