package.json
src/components/05_pages/Permissions/Permissions.js
src/components/Helpers/Loading.js
src/components/UI/index.js
src/components/UI/table.js
yarn.lock

- Enable [JSON API](https://www.drupal.org/project/jsonapi) and [Admin UI support](https://github.com/jsdrupal/drupal-admin-ui-support)modules.

#7 Permissions

---

src/actions/application.js
src/components/02_atoms/Error/Error.js
src/components/02_atoms/Message/Message.js
src/components/05_pages/Permissions/Permissions.js
src/components/05_pages/Roles/Roles.js
src/components/06_wrappers/Default/Default.js
src/reducers/application.js

I converted the current error property from the state to a more generic message which allows specifying type for the message.
Few open questions:
- How do we want to handle transporting the message type for the component? Currently it uses the variable from the actions but it didn't feel like the best approach.
- There was few instances where the old Error component was rendered directly. Should we use React error boundaries instead for handling render time errors that are blocking further rendering?
- Do we want to support multiple messages at the same time?

Allow setting a success message

---

admin_ui_support/admin_ui_support.links.menu.yml
admin_ui_support/admin_ui_support.routing.yml
admin_ui_support/admin_ui_support.services.yml
admin_ui_support/config/install/admin_ui_support.settings.yml
admin_ui_support/config/schema/admin_ui_support.schema.yml
admin_ui_support/src/Form/SettingsForm.php
admin_ui_support/src/Routing/RouteSubscriber.php
admin_ui_support/tests/src/Functional/RedirectRoutesTest.php

If you are using the React totally separately from the Drupal site you may want to disable redirecting paths from Drupal to the app.
Provides a new form at `/admin/config/admin_ui_support/settings` to enable/disable redirecting.  When the module is first enabled it will redirect.

Add configuration option to disable redirecting routes.

---

src/utils/api/api.js

The API endpoints for Role related pages seem to have gotten mangled at some point. Currently on the master branch my Role listing page does not work, and I'm unable to save the role specific permission page. This update resolves that for me.

Fix API endpoints for user roles

---

README.md

```
$ composer run-script start
A script named install would override a Composer command and has been skipped
> cd docroot && php core/scripts/drupal server
Drupal development server started: <http://127.0.0.1:8888>
This server is not meant for production use.
One time login url: <http://127.0.0.1:8888/user/reset/1/1525873677/5Bnmpogv95OSZHOj_KWPtRi5xJRQ09mjvygDmQm2Y5g/login>
Press Ctrl-C to quit the Drupal development server.
[Symfony\Component\Process\Exception\ProcessTimedOutException]
The process "cd docroot && php core/scripts/drupal server" exceeded the timeout of 3
00 seconds.
```
Possible solutions:
* Disable the timeout. This sounds like a good solution, but I argue we should teach people about ```drupal server``` instead of hiding it behind another command
* Use the actual php …

Process dies after 60 seconds

---

src/components/05_pages/Content/Content.js

Makes both action buttons dark grey. [Discussed](https://drupal.slack.com/messages/C2SJQ5FMG/convo/C2SJQ5FMG-1528804382.000427/) with @ckrina about this and she approved.

Remove secondary (red) color from edit button.

---

src/components/02_atoms/OpsModalButton/OpsModalButton.js

At the last moment when  #145 was being stitched together with the bulk operations issue the button labels where added as additional properties to the opModalButton.. this is a good thing to do 
But the annotation at the start of the class definition was not updated.
This is just a minor tidyup

Followup to #145 document properties of the new button.

---

src/components/02_atoms/OpsModalButton/OpsModalButton.js

I want to fix up a mistake I made.
When OpsModalButton was created I copied example code from the material-ui website.
It must have been from a outdated version of material-ui
When I look with chrome dev tools the presence of the bad attribute is throwning errors in the console logs
It should be a boolean not a string, and the default is the sensible option so the prop can be deleted.

keepMounted is causing errors and should be deleted

---

src/components/06_wrappers/Default/Default.js
src/tests/Nightwatch/Tests/menu.js

https://github.com/jsdrupal/drupal-admin-ui/issues/202
see main issue for the screen shot
Look at the main content page - see the scrollbars can be seen as visual blemish.
[to the left and just above the watercress table row. ]
Chrome's devtools were reporting the  'hidden' property was invalid --  hidden without the quotes is a valid property!

Remove horizontal scrollbar widget from the menu bar.(#202)

---

src/tests/Nightwatch/Tests/menu.js
src/tests/Nightwatch/globals.js

We fixed the nightwatch random failures by passing along time manually how log we want to wait for elements to appear.
For new tests we then started to pass along the same number so it seems more sensible to change the default.

change the default waiting time for elements

---

package.json
public/index.html
src/components/02_atoms/PageTitle/PageTitle.js
src/components/02_atoms/PageTitle/index.js
src/components/05_pages/AddContent/AddContent.js
src/components/05_pages/Content/Content.js
src/components/05_pages/NodeForm/index.js
yarn.lock

This create `PageTitle` component which has a side effect to change the document title. This takes into accounts requirements set on https://github.com/jsdrupal/drupal-admin-ui/issues/184.
A downside on the current approach compared to what I proposed as an alternative there is that we cannot pre-fetch the title from the component, meaning that initially the page will render using wrong page title.
Content related pages should have titles, and when navigating between pages the document title should change.

Add PageTitle component

---

src/reducers/application.js
src/reducers/content.js

The default case of the reducers returns a copy of the state, this could cause unnecessary UI updates. The PR fix the code returning the untouched state.

Let reducers default case returns the untouched state

---

.circleci/config.yml

This PR changes the Drupal installation commands for the integration test. This tries to tackle various problems at once:
1. The commands run cloned git repositories not used for testing which made following the installation steps slightly more complex than it could be.
2. Drupal was installed using the latest dev code, not the actual code being tested. This could have caused failures if we changed the installation requirements (not sure if this is the case since the tests install Drupal separately always).
3. As a side benefit this should also make the tests run a bit faster
We do need a follow-up to add usages of the commands to the demo repository to make sure all commands are being at least somewhat tested.

Improve steps used to setup Drupal for integration tests

---

src/components/06_wrappers/Default/Default.js
src/tests/Nightwatch/Tests/menu.js

https://github.com/jsdrupal/drupal-admin-ui/issues/196
screen readers are given a more semantically correct DOM structure from which to work from.
Run chrome's lighthouse accessibility tests to expose all current  failures.
Once  the PR is used the bad structure errors and warning related to the menubar disappear
Please note if you look at localhost:3000 you will see lots of errors related the main page 
there are being removed in a separate issue.( see #178 )

For screenreaders and a11y fix the menu bar.

---

admin_ui_support/composer.json

In https://github.com/jsdrupal/drupal-admin-ui/pull/216 we added the dependency on OpenAPI dev version. Now the issue we need, https://www.drupal.org/project/openapi/issues/2986679,  is the latest beta2 release.

change to openapi beta2

---

src/components/02_atoms/OpsModalButton/OpsModalButton.stories.js

https://github.com/jsdrupal/drupal-admin-ui/issues/235
run:-
yarn storybook
See new page for the OpsModalButton
The button is on the right.

#186 Add storybook for OpsModalButton wrapped in a table.

---

src/components/05_pages/Content/Content.js

The group actions menu item should be disabled if no items are selected.
- ensure you are unable to example the actions drop down when no menu items are selected

Disable actions menu item when no nodes are selected.

---

README.md
src/index.js

`react-axe` causes some outstanding performance issues, and a nasty call-stack error when sorting the content listing table.
Disable `react-axe` unless you specify a environment variable, `REACT_APP_AXE=true yarn start`
Start without `react-axe` and be amazed how fast everything is.

Hide react-axe behind an environment variable.

---

src/components/05_pages/NodeForm/UiMetadata.js

https://github.com/jsdrupal/drupal-admin-ui/issues/258
Rearranged the admin UI node form fields to look in the same order as Drupal does. Plus there was one field missing i.e Recipe Category. I have added that. (Let me know if this is not required).
Also I was not sure where to keep the "Created Date" field. For now, I've kept it at the end of the form.
- Navigate to Node Add Recipe page (/node/add/recipe), you should be able to see the same order of fields as Drupal does.
- There are few fields missing (Summary, Ingredients, and Recipe Instruction), a couple of them are editor related. So we can ignore them for now.

Rearranged node fields plus added one extra

---

src/components/05_pages/Content/Content.js

https://github.com/jsdrupal/drupal-admin-ui/issues/178
Screenreaders need at least a aria-label associated with every input element.
This is showing up as a test failure on chrome's lighthouse accessibility tests.

Fixed A11y for title Textfield (#178)

---

package.json
src/components/02_atoms/FileUpload/FileUpload.stories.js
src/components/02_atoms/Widgets/FileUploadWidget.js

https://github.com/jsdrupal/drupal-admin-ui/issues/284
1) yarn run storybook to start the storybook server
2) Open chrome's devtools view the console.
3) Visit the FileUpload widget storybook definitions
see that most of the errors are gone.
We could trap the fetchs to http://localhost:9001/url but I want to keep this PR simple and deal with that in a follow up.

Storybook: Resolve errors displayed on the console.(#284)

---

package.json

Followup to 
https://github.com/jsdrupal/drupal-admin-ui/issues/284
I screwed up ... I was experimenting with trapping and handling fetch requests for storybook widgets
I backed out some code before creating a PR. Unfortunately I did not completely back-out some changes to package.json
It is not appropriate to depend on fetch-mock yet!!!!
Sorry for the distraction.

Remove stray dependancy on fetch-mock

---

admin_ui_support/admin_ui_support.routing.yml

https://github.com/jsdrupal/drupal-admin-ui/issues/302
- Navigate to the add content page
- Try to add a recipe and get redirected to Seven
- Apply this branch, try again and get the new form

#302 Makes the node/add/x pages accesible

---

src/components/02_atoms/Widgets/FileUploadWidget.js
src/components/02_atoms/Widgets/Widgets.stories.js
src/utils/api/fieldItem.js

https://github.com/jsdrupal/drupal-admin-ui/issues/301
The visual appearance of the storybook entries for the FileUploadWidget are restored to their former glory.
UI changes ... yes
FileUploadWidget: the property value has had its data structures revamped to allow for alternate meta string on a per file basis ( During multiple uploads ).
run yarn storybook and see:
the errors are removed.
the FileUploadWidget entries are restored.

Fix bug in getItemsAsArray().

---

src/components/05_pages/AddContent/AddContent.js
src/tests/Nightwatch/Tests/AddContent.js

https://github.com/jsdrupal/drupal-admin-ui/issues/342
as per instruction on the home page enable aXe with : -
REACT_APP_AXE=true yarn start
visit http://localhost:3000/node/add/recipe
in the parent issue I detailed a axe report that highlights a issue with the DOM structure which confounds screen readers.
With this PR applied the aXe warnings go away.
Please note a small amount of css is needed to bypass a underline text issue common to many  LINK elements.

List a11y issue

---

src/components/02_atoms/Widgets/Widgets.stories.js

https://github.com/jsdrupal/drupal-admin-ui/issues/364
a) I have put OptionsSelect in alphabetical order.
b) I  have added a inputProps object ... a required object.
a) Start the storbook server with 
yarn storybook
b) visit
http://localhost:9001/
open the widgets tab, select OptionsSelect
see that the page no longer shows errors.

Storybook: OptionsSelect 'allowed_values' needs updating (#364)

---

src/components/02_atoms/PageTitle/PageTitle.js

Sometimes the document title wasn't set because of an overly strict type check. This should improve the situation and make the title visible.

Make type check in PageTitle component more accurate

---

src/components/05_pages/NodeAddForm/index.js
src/components/05_pages/NodeEditForm/index.js
src/components/05_pages/NodeForm/index.js

Move onSave from the NodeForm to it's parent so that changing it separately for entity creation and editing is possible.

Make onSave specific to the action entity form is tied for

---

src/components/02_atoms/InlineMessage/InlineMessage.stories.js
src/components/02_atoms/Widgets/DatetimeTimestamp.js
src/components/02_atoms/Widgets/Widgets.stories.js

https://github.com/jsdrupal/drupal-admin-ui/issues/390
Fixes console errors seen while inspecting storybook definition.
( see the parent issue for details ) 
Please note 
(#333) will resolve the remaining storybook console errors.
The default value of a widget is corrected.... so this is a DX/interface change... if you know what I mean

Storybook: Update component properties #390

---

src/components/02_atoms/Widgets/FileUploadWidget.js

https://github.com/jsdrupal/drupal-admin-ui/issues/333
This reduces one of the many  warnings that appear on the console log when visiting 
for http://localhost:3000/node/add/recipe
[ The warnings were also visible when looking at the storybook definitions of the FileUploadWidget ]
The parent issue has a description of the bug. But here is a short summary of the solution.
There were two bugs one hiding behind the other
The first bug was a misconception... 
PropTypes.oneOf() incorrectly instead of PropTypes.oneOfType() 
The second bug was just to get the PropTypes to make sense
the id which is required is different in the two distinct cases.

FileUploadWidget: Invalid prop definition for multiple uploads (#333)

---

src/components/05_pages/Content/ConfirmationDialog.js

https://github.com/jsdrupal/drupal-admin-ui/issues/416
Native list elements replaced with material-ui elements and Appropriate nesting added.
1. Go to `/`
2. Select a couple of checkboxes.
3. The warning message must not appear.

Native HTML replaced with Material Ui and paragraph wrapper removed.

---

src/components/05_pages/Content/ConfirmationDialog.js

https://github.com/jsdrupal/drupal-admin-ui/issues/421
Changed the list style to bullets and removed '-' from list items in confirmation dialog.
1. Select the content on which action needs to be performed.
2. On Actions tab, select any action e.g : Delete content.
3. Click Apply button.
4. Confirmation dialog list contains bullets instead of '-'.

issue-421: Confirmation dialog text styling fixed.

---

src/components/02_atoms/FileUpload/FileUpload.js

#442 
Upload file format which is not acceptable and checks the Error message theme.

Issue-442: Fixed Error messages not rendering properly for File upload widget.

---

src/components/05_pages/NodeAddForm/index.js
src/components/05_pages/NodeEditForm/index.js
src/components/05_pages/NodeForm/index.js
src/routes.js

Routes/Components that need props from React Router are handled a bit different than those that do not. There is no reason for this. This moves the route matching params logic to either `NodeEdit` or `NodeAdd` instead of the actual router.

Cleanup how route params are handled.

---

src/actions/schema.js

We're currently using `Promise.all()` instead of `all([])` from `redux-saga`. https://redux-saga.js.org/docs/api/#alleffects---parallel-effects
- Ensure schema is still fetched correctly.

Use saga/effects all instead of Promise.all()

---

src/components/02_atoms/MultipleFields/MultipleFields.js

https://github.com/jsdrupal/drupal-admin-ui/issues/456
MultipleFields -- the button at the end of the list structure is incorrectly buried within the list structure itself.
Enable A11y testing 
REACT_APP_AXE=true yarn start
Visit 
http://localhost:3000/node/add/recipe
Observe that there are less A11y warnings.

MultipleFields - A11y adjust DOM structure #456

---

src/components/05_pages/TaxonomyTermsOverview/TaxonomyTermsOverview.js

#472 
Go to taxonomy term overview page.. click on any action link related to taxonomy term it will redirect a user to the respective page

issue-472: Broken taxonomy term action links fixed.

---

src/components/05_pages/TaxonomyTermsOverview/TaxonomyTermsOverview.js

#470 
Visit taxonomy overview page and click on add button in the right bottom corner, it will take a user to add new term page.

Add new term button provided on taxonomy overview page.

---

src/tests/Nightwatch/Tests/TaxonomyPage.js

#490 
execute `yarn nightwatch` taxonomyPage test should be passing.

IS-490: Adding nigthwatch test for taxonomy page

---

src/components/05_pages/NodeForm/index.js

https://github.com/jsdrupal/drupal-admin-ui/issues/484
requestShema PropType removed from NodeForm as it is not required.

requestShema PropType removed from NodeForm.

---

packages/admin-ui/src/components/05_pages/Permissions/Permissions.js

https://github.com/jsdrupal/drupal-admin-ui/issues/522
This is a very very minor   issue.
I am using a stricter linter tool, as I slowly convert this project to typescript.
This is just an isolated boolean type mismatch picked up by the new tooling.
( see the parent issue. for a detailed explanation )

Permission: "disabled" must be a boolean #522

---

demo/composer.json

https://github.com/jsdrupal/drupal-admin-ui/issues/530
We should specify Drupal 8.7 everywhere .

Consistent use of D8.7 #530

---

packages/admin-ui/src/App.js

https://github.com/jsdrupal/drupal-admin-ui/issues/527
This is just a minor issue 
Here is a summary of the originating issue.
As I work on the typescript branch -- the lifecycle of the storedState  variable is driving the linter crazy.
It is initialized as a object, assigned a string, and the converted back to a object as part of a JSON.parse() 
The solution is to split the variable into two.

Stringified state

---

.eslintrc.json

https://github.com/jsdrupal/drupal-admin-ui/issues/552
I want to use ENUMs in a upcoming PR - #538 Make MessageSeverity constants an ENUM
but first we need to move the ES6
Here is a quote from the eslint documentation showing that the current default is es5
https://eslint.org/docs/2.0.0/user-guide/configuring
ecmaVersion - set to 3, 5 (default), or 6 to specify the version of ECMAScript you want to use.

Move from es5 to es6 to support ENUMs and MAPs. #552

---

demo/composer.json

https://github.com/jsdrupal/drupal-admin-ui/issues/532
When the workspace modifications were committed the location of .env changes 
the devify command did not account for this ... 
I am just restoring functionality.

devify .env has moved #532

---

packages/admin-ui/src/components/05_pages/AddContent/AddContent.js

https://github.com/jsdrupal/drupal-admin-ui/issues/555
The parent issue identifier that typescript files were not being linted. Another PR rename files containing typescript to AddContent.test.js and  AddContent.test.jsx 
This PR now fixes one of the outstanding lint errors 
Markup is wrapped in a ListItemText element and so as we sanitize it is inappropriate to use Markup's default of a div as an internal wrapper.
https://github.com/jsdrupal/drupal-admin-ui/issues/555#issuecomment-441188250
Here is the lint warning
> Warning: validateDOMNesting(...): cannot appear as a descendant of <p>.
looking at the valid values for tagName in  Markup -- "span" or "fragment" are the only possibilities 
fragment has the advantage of dissolving into nothing.

AddContent: Replace div with fragment

---

packages/admin-ui/src/components/05_pages/Content/Content.js

https://github.com/jsdrupal/drupal-admin-ui/issues/643
Visit /admin/content and observe the alignment of the form controls after the text field. The select fields are not vertically aligned. This fix applies margin to the top and bottom of those fields and removes margin on the right so the spacing between the fields is even.

[#643] Correct the margins applied to the formControls for admin/content

---

packages/admin-ui/src/index.js

https://github.com/jsdrupal/drupal-admin-ui/issues/645
You can only see this error when the api is not available or has not yet been set up. When setting up the project for the first time I noticed that `drupal_admin_ui_node` reported that the local URL was available and I command clicked it. This loaded the page before Drupal was fully installed resulting in an error that `console.err is not a function`. Once Drupal had finished installing the error disappeared because Drupal was able to fetch It's routes and start the react app.

[#645] Fix typo, console.err should be console.error

---

packages/admin-ui/package.json

This reverts commit d87a6bdd7c53d4165dbc6af91f3de36e024d0f5f.
This commit was introduced in https://github.com/jsdrupal/drupal-admin-ui/pull/693 by Greenkeeper. The update to react-redux causes the build process to work and `yarn workspace admin-ui build`, `yarn workspace admin-ui start` ends up in an unusable application.
Reverting to version `^5.0.7` fixes the problem.

Revert "fix(package): update react-redux to version 7.0.0"

---

packages/components/.storybook/addons.js
packages/components/.storybook/config.js
packages/components/package.json

This sets up Storybook for the `packages/components/` directory. The config is copied from `packages/admin-ui/.storybook/` directory. And required bits added to package.json.
I made one config change, and am limiting this to finding *.stories.js files in package/components/ because some of them in packages/admin-ui/ appear to be broken.
To test ... `cd packages/components/; yarn run storybook`.
Granted, there are no stories to build yet. It is working in my tests.
This will be required to add storybook integration when creating components in issues like #691, and #662

Add storybook and related config to packages/components/.

---

packages/components/src/Components/FormElements/FormElements.stories.js
packages/components/src/Components/FormElements/Label.js
packages/components/src/index.js

https://github.com/jsdrupal/drupal-admin-ui/issues/691
Add a generic `<Label/>` component for use on forms.
There's not really anything to see yet since the component isn't used anywhere. You can run storybook to see it in action though.
This is probably also not complete as this is just a first pass at figuring out how to create one of these generic form components. It's also my first go at creating a component for this project so feel free to suggest alternative approaches to anything. :)
Example use:
```jsx
<Label htmlFor="username" required={true} htmlAttributes={['data-username' => 'snorfblat']}>Username:</Label>
```
In order to allow someone to pass along generic HTML attributes to the component I've added an `htmlAttributes` prop. With the idea that you populate that with any …

[#691] First pass at adding a generic <Label> component

---

.eslintrc.json

https://github.com/jsdrupal/drupal-admin-ui/issues/752
.tslintrc.json incorrectly has the following duplicate keys parser and parserOptions
Removed the keys which are being overridden.

eslintrc.json: Removed duplicate parserOptions
